#!/usr/bin/env tsx
/**
 * Bootstrap EN translations for DB entity fields.
 * Reads products, news, applications, services from DB.
 * For each VI jsonb field with missing EN counterpart, emits a SQL UPDATE
 * with a "TODO: translate" marker so a human can review before applying.
 *
 * Output: scripts/data-en-bootstrap.sql
 * Apply manually: psql $DATABASE_URL -f scripts/data-en-bootstrap.sql
 *
 * DO NOT call external translation APIs — output is draft only.
 */
import fs from "node:fs";
import path from "node:path";
import { neon } from "@neondatabase/serverless";

// Load .env manually (tsx doesn't auto-load it)
const envPath = path.join(process.cwd(), ".env");
if (fs.existsSync(envPath)) {
  const lines = fs.readFileSync(envPath, "utf8").split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, "");
    if (!process.env[key]) process.env[key] = val;
  }
}

const dbUrl = process.env.DATABASE_URL;
if (!dbUrl) {
  console.error("DATABASE_URL not set. Exiting.");
  process.exit(1);
}

const sql = neon(dbUrl);
const OUTPUT = path.join(process.cwd(), "scripts", "data-en-bootstrap.sql");

function escapeSql(val: string): string {
  return val.replace(/'/g, "''");
}

function draftEn(viText: string): string {
  return `TODO: translate — ${viText.slice(0, 120)}${viText.length > 120 ? "…" : ""}`;
}

type I18nText = { vi: string; en?: string | null };

// Schema uses singular table names + slug primary key.
interface Product {
  slug: string;
  name: I18nText;
  desc: I18nText;
}

interface NewsItem {
  slug: string;
  title: I18nText;
  excerpt: I18nText;
}

interface Application {
  slug: string;
  title: I18nText;
  summary: I18nText;
}

interface Service {
  slug: string;
  title: I18nText;
}

async function run(): Promise<void> {
  const lines: string[] = [
    "-- data-en-bootstrap.sql",
    "-- Auto-generated by scripts/translate-data.ts",
    "-- Review ALL TODO markers before applying.",
    "-- Apply: psql $DATABASE_URL -f scripts/data-en-bootstrap.sql",
    "",
  ];

  // Products — table `product`, column `desc`, key `slug`
  const products = (await sql`
    SELECT slug, name, "desc" FROM product ORDER BY slug
  `) as Product[];

  lines.push("-- ============================================================");
  lines.push("-- PRODUCTS");
  lines.push("-- ============================================================");

  for (const p of products) {
    const nameEn = p.name?.en;
    const descEn = p.desc?.en;
    const needsName = !nameEn || nameEn.trim() === "";
    const needsDesc = !descEn || descEn.trim() === "";

    if (needsName || needsDesc) {
      const newName: I18nText = {
        vi: p.name.vi,
        en: needsName ? draftEn(p.name.vi) : (p.name.en ?? ""),
      };
      const newDesc: I18nText = {
        vi: p.desc.vi,
        en: needsDesc ? draftEn(p.desc.vi) : (p.desc.en ?? ""),
      };
      lines.push(
        `UPDATE product SET name = '${escapeSql(JSON.stringify(newName))}', "desc" = '${escapeSql(JSON.stringify(newDesc))}' WHERE slug = '${escapeSql(p.slug)}';`
      );
    }
  }

  // News — table is already `news`, key `slug`
  const news = (await sql`
    SELECT slug, title, excerpt FROM news ORDER BY slug
  `) as NewsItem[];

  lines.push("");
  lines.push("-- ============================================================");
  lines.push("-- NEWS");
  lines.push("-- ============================================================");

  for (const n of news) {
    const titleEn = n.title?.en;
    const excerptEn = n.excerpt?.en;
    const needsTitle = !titleEn || titleEn.trim() === "";
    const needsExcerpt = !excerptEn || excerptEn.trim() === "";

    if (needsTitle || needsExcerpt) {
      const newTitle: I18nText = {
        vi: n.title.vi,
        en: needsTitle ? draftEn(n.title.vi) : (n.title.en ?? ""),
      };
      const newExcerpt: I18nText = {
        vi: n.excerpt.vi,
        en: needsExcerpt ? draftEn(n.excerpt.vi) : (n.excerpt.en ?? ""),
      };
      lines.push(
        `UPDATE news SET title = '${escapeSql(JSON.stringify(newTitle))}', excerpt = '${escapeSql(JSON.stringify(newExcerpt))}' WHERE slug = '${escapeSql(n.slug)}';`
      );
    }
  }

  // Applications — table `application`, key `slug`
  const apps = (await sql`
    SELECT slug, title, summary FROM application ORDER BY slug
  `) as Application[];

  lines.push("");
  lines.push("-- ============================================================");
  lines.push("-- APPLICATIONS");
  lines.push("-- ============================================================");

  for (const a of apps) {
    const titleEn = a.title?.en;
    const summaryEn = a.summary?.en;
    const needsTitle = !titleEn || titleEn.trim() === "";
    const needsSummary = !summaryEn || summaryEn.trim() === "";

    if (needsTitle || needsSummary) {
      const newTitle: I18nText = {
        vi: a.title.vi,
        en: needsTitle ? draftEn(a.title.vi) : (a.title.en ?? ""),
      };
      const newSummary: I18nText = {
        vi: a.summary.vi,
        en: needsSummary ? draftEn(a.summary.vi) : (a.summary.en ?? ""),
      };
      lines.push(
        `UPDATE application SET title = '${escapeSql(JSON.stringify(newTitle))}', summary = '${escapeSql(JSON.stringify(newSummary))}' WHERE slug = '${escapeSql(a.slug)}';`
      );
    }
  }

  // Services — table `service`, key `slug`
  const services = (await sql`
    SELECT slug, title FROM service ORDER BY slug
  `) as Service[];

  lines.push("");
  lines.push("-- ============================================================");
  lines.push("-- SERVICES");
  lines.push("-- ============================================================");

  for (const s of services) {
    const titleEn = s.title?.en;
    const needsTitle = !titleEn || titleEn.trim() === "";

    if (needsTitle) {
      const newTitle: I18nText = {
        vi: s.title.vi,
        en: draftEn(s.title.vi),
      };
      lines.push(
        `UPDATE service SET title = '${escapeSql(JSON.stringify(newTitle))}' WHERE slug = '${escapeSql(s.slug)}';`
      );
    }
  }

  lines.push("");
  fs.writeFileSync(OUTPUT, lines.join("\n"), "utf8");
  console.log(`Written to ${OUTPUT}`);
  console.log(
    "Review all TODO markers, replace with real translations, then apply with: psql $DATABASE_URL -f scripts/data-en-bootstrap.sql"
  );
}

run().catch((err: unknown) => {
  console.error("translate-data failed:", err);
  process.exit(1);
});
